name: Publish Python Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine

    - name: Build the distribution
      run: |
        python setup.py sdist bdist_wheel

    - name: Publish to PyPI
      env:
        PYPI_USERNAME: PaNDa2code
        PYPI_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        python -m twine upload dist/* -u $PYPI_USERNAME -p $PYPI_PASSWORD
